# Generated by Django 3.1.7 on 2021-03-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('name_page', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('listed', models.BooleanField()),
            ],
        ),
    ]
