# Generated by Django 3.1.7 on 2021-03-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
