# Generated by Django 3.1.7 on 2021-03-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pages_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='name_page',
            new_name='page_name',
        ),
    ]
